#!/usr/bin/env bash
# Bootstrap health check for a generated Agentic SDLC project.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROFILE_FILE="$ROOT/.agent/bootstrap-profile.json"
PROFILE_VALIDATOR="$ROOT/scripts/validate-installation-profile.py"
ACTIVE_WORK_BLOCK="$ROOT/.agent/active-work-block.json"
DEFAULT_WORK_BLOCK="$ROOT/.agent/active-work-block.default.json"

echo "==> Bootstrap: verifying Agentic SDLC layer at $ROOT"

[ -f "$PROFILE_FILE" ] || {
  echo "FAIL: missing .agent/bootstrap-profile.json" >&2
  exit 1
}
[ -f "$PROFILE_VALIDATOR" ] || {
  echo "FAIL: missing scripts/validate-installation-profile.py" >&2
  exit 1
}
[ -f "$DEFAULT_WORK_BLOCK" ] || {
  echo "FAIL: missing .agent/active-work-block.default.json" >&2
  exit 1
}

# Validate portable selected/unselected composition and the tracked BLOCKED
# Work Block default before creating or restoring any ignored local state.
python3 "$PROFILE_VALIDATOR" "$ROOT"

# Projects may use memory_bank/ (framework default) or memory-bank/ (legacy).
MEMORY_DIR="memory_bank"
HAS_HYPHEN=false
HAS_UNDERSCORE=false
[ -d "$ROOT/memory-bank" ] && HAS_HYPHEN=true
[ -d "$ROOT/memory_bank" ] && HAS_UNDERSCORE=true

if $HAS_HYPHEN && ! $HAS_UNDERSCORE; then
  MEMORY_DIR="memory-bank"
  echo "  DETECTED: memory-bank/ (hyphen convention)"
elif $HAS_UNDERSCORE && ! $HAS_HYPHEN; then
  echo "  Using: memory_bank/ (underscore convention)"
elif $HAS_HYPHEN && $HAS_UNDERSCORE; then
  if [ -f "$ROOT/memory-bank/activeContext.md" ] || [ -f "$ROOT/memory-bank/productContext.md" ]; then
    MEMORY_DIR="memory-bank"
    echo "  DETECTED: both exist. Using memory-bank/ (has project content)."
  else
    echo "  Both exist. Using memory_bank/ (framework default)."
  fi
else
  echo "  Creating: memory_bank/ (framework default)"
fi

mkdir -p "$ROOT/$MEMORY_DIR/snapshots"

ensure_operational_file() {
  local relative="$1"
  local title="$2"
  local path="$ROOT/$MEMORY_DIR/$relative"
  if [ ! -f "$path" ]; then
    printf '# %s\n\n' "$title" > "$path"
    echo "  RESTORED: $MEMORY_DIR/$relative"
  fi
}

ensure_operational_file "context.md" "Current Context"
ensure_operational_file "progress.md" "Progress"
ensure_operational_file "decisions.md" "Operational Decisions"
ensure_operational_file "orchestrator-log.md" "Orchestrator Log"
ensure_operational_file "review-log.md" "Review Log"
ensure_operational_file "external-team-log.md" "External Team Log"
touch "$ROOT/$MEMORY_DIR/snapshots/.gitkeep"

if [ ! -f "$ACTIVE_WORK_BLOCK" ]; then
  cp "$DEFAULT_WORK_BLOCK" "$ACTIVE_WORK_BLOCK"
  echo "  RESTORED: .agent/active-work-block.json (BLOCKED default)"
fi

INSTALLATION_PROFILE="$(python3 - "$PROFILE_FILE" <<'PY'
import json
import pathlib
import sys
value = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
print(value["resolved_profile"])
PY
)"
RUNTIMES="$(python3 - "$PROFILE_FILE" <<'PY'
import json
import pathlib
import sys
value = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
print(", ".join(value["runtimes"]))
PY
)"

mkdir -p "$ROOT/.agent"
cat > "$ROOT/.agent/project-config.md" << PROJECTCONFIG
# Project Configuration

> Auto-generated by scripts/bootstrap.sh. Do not edit manually.

- **MEMORY_DIR:** \`$MEMORY_DIR\`
- **INSTALLATION_PROFILE:** \`$INSTALLATION_PROFILE\`
- **INSTALLED_RUNTIME_GUIDANCE:** \`$RUNTIMES\`

The installation profile records scaffold composition only. It does not grant
Work Block authority, integration admission, credentials, or side-effect
permission.
PROJECTCONFIG

echo "==> Agentic SDLC layer: OK"

echo ""
echo "==> Dev environment checks..."
if [ -d "$ROOT/node_modules" ]; then
  echo "  OK: node_modules/"
else
  echo "  WARN: node_modules/ missing — install dependencies when this project requires them"
fi

if [ -n "${DATABASE_URL:-}" ]; then
  echo "  OK: DATABASE_URL is set"
elif [ -f "$ROOT/.env" ] && grep -q "DATABASE_URL" "$ROOT/.env" 2>/dev/null; then
  echo "  OK: DATABASE_URL found in .env"
else
  echo "  WARN: DATABASE_URL not set — database-dependent checks may be blocked"
fi

echo "==> Dev environment checks done"
